<?php
include_once ("../../funciones/f_html.php");
session_start();
$_SESSION['pagina_secundaria'] = 'politicayprivacidad';
cabecera_inicio();
incluir_general(1,1);//jquery,validaciones
?>
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Cabin">
<link rel="stylesheet" type="text/css" href="css/paginas_standar.css" />
<link rel="stylesheet" type="text/css" href="../../../sweetalert-master/lib/sweet-alert.css" />
<script src="../../../sweetalert-master/lib/sweet-alert.min.js" type="text/javascript"></script>
<script src="javascript/contacto.js" type="text/javascript"></script>
<link href="../../css/hover.css" rel="stylesheet" media="all">
<!--
-->
<?php
cabecera_fin();
?>
<div class="principal">
	<div class="izquierdo">&nbsp;</div>
    <div class="hvr-glow" id="contenido">
        <div class="central">
        	<label class="caja_texto">&nbsp;</label><label class="caja_input">&nbsp;</label><label id="errorTextarea" class="caja_error">&nbsp;</label>
            <label class="titulo">CONDICIONES DE USO Y POL&Iacute;TICA DE PRIVACIDAD DE MITORNEODEPADEL</label>
            <div class="texto_mostrar">
            	<label class="titulo_condiciones">1. INTRODUCCI&Oacute;N</label>
            	<label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El uso de nuestro Portal implica la aceptaci&oacute;n y adhesi&oacute;n a todas nuestras Condiciones de Uso y a nuestra Pol&iacute;tica de Privacidad. Te recomendamos que las leas detenidamente.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Nuestros Servicios son muy diversos, por lo que en ocasiones se pueden aplicar condiciones o requisitos de productos adicionales (incluidas restricciones de edad). Las condiciones adicionales estar&aacute;n disponibles junto con los Servicios pertinentes y formar&aacute;n parte del acuerdo que estableces con Mitorneodepadel al usar nuestros servicios.</label>
                <label class="titulo_condiciones">2. DEFINICI&Oacute;N DEL SERVICIO DE MITORNEODEPADEL</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El Servicio de Miltorneodepadel consiste en la gesti&oacute;n, por parte del usuario administrador de torneos de padel profesionales o particulares. El administrador interact&uacute;a directamente con los jugadores que se inscriben en sus torneos.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Para registrarse como usuario administrador de torneos en Mitorneodepadel se ha de completar el formulario de "Crear Nuevo Torneo". Una vez seleccionado el tipo de torneo, deber&aacute; rellenar los datos del formulario y se crear&aacute; un nuevo usuario, que recibir&aacute; un e-mail de notificaci&oacute;n donde deber&aacute; activar su cuenta. A partir de ese momento los datos aportados por el administrador quedar&aacute;n registrados, y ser&aacute;n tratados de conformidad con nuestra Pol&iacute;tica de Privacidad con total exclusividad y privacidad para esta web. Con el correo electr&oacute;nico que ha facilitado el usuario administrador y la clave de acceso, puede acceder a su &aacute;rea seleccionando "Administrador" en el inicio e insertar el e-mail y contrase&ntilde;a con los que se registr&oacute;.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Para registrarse como usuario patrocinador en Mitorneodepadel se ha de completar el formulario de "Crear Patrocinador". Puede acceder directamente a su panel de control seleccionando "Patrocinador" e insertando el e-mail y contrase&ntilde;a, una vez dentro puede seleccionar las ciudades donde quiere patrocinarse y el tipo de suscripci&oacute;n (pagos realizados a trav&eacute;s de paypal).</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Para registrarse como usuario jugador en Mitorneodepadel se ha de completar el formulario al inscribirse por primera vez en un torneo y divisi&oacute;n correspondiente seleccionado la provincia, municipio, nombre de torneo y divisi&oacute;n. Para el resto de inscripciones solo es necesario el e-mail y nombre. Puede acceder directamente a su panel de control seleccionando "Jugador" e insertando el e-mail y contrase&ntilde;a, una vez dentro puede gestionar todos sus pagos realizados o por realizar (siempre que est&eacute; disponible el pago online habilitado por el administrador) as&iacute; como gestionar las incripciones en torneos, contactar con los administradores de los torneos.</label>
                <label class="titulo_condiciones">3. USO DEL PORTAL Y SUS SERVICIOS</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">Los usuarios se comprometen a utilizar el Portal, sus contenidos y servicios conforme con</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">1.- La Ley o cualesquiera otras normas del ordenamiento jur&iacute;dico aplicable</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">2.- Las presentes Condiciones de Uso</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">3.- Las Normas de Funcionamiento</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">4.- Las buenas costumbres</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">5.- El orden p&uacute;blico</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Asimismo, los usuarios se comprometen expresamente a no destruir, alterar, inutilizar o, de cualquier otra forma, da&ntilde;ar los datos, programas o documentos electr&oacute;nicos y dem&aacute;s que se encuentren en el Portal de www.mitorneodepadel.es.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los usuarios se comprometen a no obstaculizar el acceso de otros usuarios al servicio de acceso mediante el consumo masivo de los recursos inform&aacute;ticos a trav&eacute;s de los cuales Mitorneodepadel presta el servicio, as&iacute; como realizar acciones que da&ntilde;en, interrumpan o generen errores en dichos sistemas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los usuarios se comprometen a no utilizar en este portal ning&uacute;n material de car&aacute;cter ofensivo, abusivo o perjucidial contra terceras personas registradas o no en el portal y que sean contrarias a la ley, el orden p&uacute;blico o que causen o sean susceptibles de causar cualquier tipo de alteraci&oacute;n en los sistemas inform&aacute;ticos de Mitorneodepadel o de terceros.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Al contactar los usuarios aceptan que se les env&iacute;e emails al correo electr&oacute;nico solicitando informaci&oacute;n, consultas o preguntas.</label>
                <label class="titulo_condiciones">4. PROPIEDAD INTELECTUAL E INDUSTRIAL</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">El Portal aloja contenidos tanto propios como contenidos creados por los usuarios. El Portal est&aacute; protegido por leyes de propiedad intelectual y por los tratados internacionales en la materia. El contenido que se muestra en o a trav&eacute;s del sitio web est&aacute; protegido en su condici&oacute;n de obra colectiva y / o compilaci&oacute;n, de acuerdo con las leyes de propiedad intelectual y los tratados internacionales sobre la materia.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Salvo que fuera autorizado por Mitorneodepadel o a menos que ello resulte legalmente permitido, el usuario no podr&aacute; copiar, modificar, distribuir, vender, alquilar o explotar de cualquier otra forma contenidos del Portal. Asimismo el usuario no puede llevar a cabo operaciones de desensamblaje o descompilaci&oacute;n, ingenier&iacute;a inversa o cualquier otra operaci&oacute;n destinada a obtener cualquier c&oacute;digo fuente contenido en este Portal.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Al subir fotograf&iacute;as al Portal, los usuarios ceden a Mitorneodepadel los derechos de explotaci&oacute;n de propiedad intelectual sobre las mismas, por lo que Mitorneodepadel podr&aacute; eliminarlas en casos en los que se infrinjan las normas de buen uso.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los usuarios garantizan que son plenos titulares de los derechos que se ceden a Mitorneodepadel en virtud de esta cl&aacute;usula, y que la eliminaci&oacute;n de los mismos por Mitorneodepadel no supondr&aacute; violaci&oacute;n alguna de derechos de propiedad intelectual, ni de imagen, ni, en general, de ninguna otra clase, que correspondan a cualesquiera terceros, oblig&aacute;ndose a indemnizar y a mantener indemne a Mitorneodepadel en caso de infracci&oacute;n.</label>
                <label class="titulo_condiciones">5. EXCLUSI&Oacute;N DE GARANTIAS Y RESPONSABILIDAD</label>
                <label class="titulo_condiciones">A. Disponibilidad y Continuidad del Portal y los Servicios</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel no garantiza la disponibilidad, el acceso y/o la continuidad del funcionamiento del Portal y de sus Servicios. Asimismo, Mitorneodepadel no ser&aacute; responsable, con los l&iacute;mites establecidos por la Ley, de los da&ntilde;os y perjuicios causados al Usuario como consecuencia de la indisponibilidad, fallos de acceso y falta de continuidad del Portal y de sus Servicios.</label>
                <label class="titulo_condiciones">B. Contenidos y Servicios de Mitorneodepadel</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel responder&aacute; &uacute;nica y exclusivamente de los Servicios que preste por s&iacute; misma y de los contenidos directamente originados por Mitorneodepadel e identificados con su copyright. Dicha responsabilidad quedar&aacute; excluida en los casos en que concurran causas de fuerza mayor o en los supuestos en que la configuraci&oacute;n de los equipos del Usuario no sea la adecuada para permitir el correcto uso de los servicios de Internet prestados por Mitorneodepadel.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Sin perjuicio de lo dispuesto, la posible responsabilidad de Mitorneodepadel frente al usuario o frente a terceros se limita al  precio total del servicio contratado que origin&oacute; la responsabilidad, con exclusi&oacute;n, en todo caso, de cualquier tipo de responsabilidad por da&ntilde;os indirectos o por lucro cesante..</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El Portal no se hace responsable de la posible aparici&oacute;n de torneos indexados en buscadores ajenos al portal, una vez se hayan dado de baja de nuestras bases de datos.</label>
                <label class="titulo_condiciones">C. Contenidos y Servicios de Terceros</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel no revisa o controla previamente, aprueba ni hace propios los contenidos, productos, servicios, opiniones, comunicaciones, datos, archivos y cualquier clase de informaci&oacute;n de terceros recogidos en el Portal. Asimismo, no garantiza la licitud, fiabilidad, utilidad, veracidad, exactitud, exhaustividad y actualidad de los contenidos, informaciones y servicios de terceros en el Portal. Mitorneodepadel tampoco garantiza de ninguna forma que los Usuarios del Portal utilicen los contenidos y/o servicios del mismo conforme con la ley, las normativas aplicables, el orden publico ni las presentes Condiciones de Uso.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel no se responsabiliza de los contenidos volcados o los actos cometidos por otros usuarios. Tampoco se responsabiliza de cualquier da&ntilde;o o perjuicio como consecuencia de la presencia de virus u otros elementos en los contenidos y servicios prestados por terceros. Asimismo Mitorneodepadel no responder&aacute; de los da&ntilde;os y perjuicios de cualquier naturaleza derivados del uso negligente o malintencionado de las cuentas de correo electr&oacute;nico utilizadas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;En cualquier caso Mitorneodepadel no ser&aacute; responsable, ni indirectamente ni subsidiariamente, de la perdida econ&oacute;mica o reputaci&oacute;n, ni de ninguna clase de da&ntilde;os especiales, indirectos o emergentes, resultantes de la utilizaci&oacute;n del sitio web por parte del usuario.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;La exoneraci&oacute;n de responsabilidad se&ntilde;alada en el p&aacute;rrafo anterior ser&aacute; de aplicaci&oacute;n en el caso de que Mitorneodepadel no tenga conocimiento efectivo de que la actividad o la informaci&oacute;n almacenada es il&iacute;cita o de que lesiona bienes o derechos de un tercero susceptibles de indemnizaci&oacute;n, o si la tuviesen act&uacute;e con diligencia para retirar los datos y contenidos o hacer imposible el acceso a ellos.</label>
                <label class="titulo_condiciones">6. CONTRATACI&Oacute;N DE SERVICIOS VINCULADOS A PATROCINADOR</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;La contrataci&oacute;n del servicio "Patrocinador" vinculado a un anuncio publicado en el Portal s&oacute;lo producir&aacute; efectos DURANTE el periodo de vigencia del anuncio.</label>
                <label class="titulo_condiciones">7. CONTRATACI&Oacute;N CON TERCEROS A TRAV&Eacute;S DEL PORTAL</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El Usuario Administrador reconoce y acepta que cualquier relaci&oacute;n contractual o extracontractual que formalice con los jugadores/as o anunciantes, as&iacute; como su participaci&oacute;n en torneos o servicios, se entienden realizados &uacute;nica y exclusivamente entre el Usuario administrador y jugadores/as o anunciantes. El Usuario administrador acepta por lo tanto que Mitorneodepadel no tiene ning&uacute;n tipo de responsabilidad sobre los da&ntilde;os o perjuicios de cualquier naturaleza ocasionados con motivo de sus negociaciones, conversaciones y/o relaciones contractuales o extracontractuales con los jugadores/as, anunciantes o terceras personas f&iacute;sicas o jur&iacute;dicas contactadas a trav&eacute;s del Portal.</label>
                <label class="titulo_condiciones">8. ENLACES DE TEXTO Y ENLACES GR&Aacute;FICOS</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El Portal pone a disposici&oacute;n de sus usuarios administradores y patrocinadores dispositivos t&eacute;cnicos de enlace de texto y/o enlaces gr&aacute;ficos que permiten a los usuarios el acceso a p&aacute;ginas web titularidad de otras entidades. Estos enlaces est&aacute;n debidamente se&ntilde;alados como publicidad en el Portal.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los usuarios previamente autorizados reconocen y aceptan que la utilizaci&oacute;n de los contenidos de las p&aacute;ginas web enlazadas ser&aacute; bajo su exclusivo riesgo y responsabilidad y exonera al portal Mitorneodepadel de cualquier responsabilidad sobre disponibilidad t&eacute;cnica de las p&aacute;ginas web enlazadas, la calidad, fiabilidad, exactitud y/o veracidad de los servicios, informaciones, elementos y/o contenidos a los que el usuario pueda acceder en las mismas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel no ser&aacute; responsable indirecta ni subsidiariamente de los da&ntilde;os y perjuicios de cualquier naturaleza derivados de a) el funcionamiento, indisponibilidad, inaccesibilidad y la ausencia de continuidad de las p&aacute;ginas web enlazadas; b) la falta de mantenimiento y actualizaci&oacute;n de los contenidos y servicios contenidos en las p&aacute;ginas web enlazadas; c) la falta de calidad, inexactitud, ilicitud, inutilidad de los contenidos y servicios de las p&aacute;ginas web enlazadas.</label>
                <label class="titulo_condiciones">9. DERECHO DE LIMITAR O PONER FIN AL SERVICIO DE MITORNEODEPADEL</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel se reserva el derecho, ejercitable en cualquier momento y de modo discrecional a rechazar cualquier anuncio o compromiso de ubicaci&oacute;n de un anuncio o torneo en una localidad determinada. Mitorneodepadel tambi&eacute;n se reserva el derecho de eliminar cualquier anuncio o torneo del Portal sin necesidad de avisar previamente a los usuarios y/o anunciantes siempre que infrinjan las normas de funcionamiento.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel puede denegar o poner fin a su servicio y adoptar medidas t&eacute;cnicas y legales para mantener a los usuarios alejados del Portal si creemos que est&aacute;n creando problemas o actuando de forma contraria al esp&iacute;ritu o la forma de nuestras normas y condiciones de uso, todo ello con independencia de cualquier pago realizado por el uso del Portal o servicios complementarios. Sin embargo, decidamos o no retirar el acceso al sitio web de un usuario, no aceptamos ninguna responsabilidad por el uso no autorizado o ilegal del sitio web por los usuarios, tal y como se describe en los p&aacute;rrafos anteriores.</label>
                <label class="titulo_condiciones">10. INDEMNIZACI&Oacute;N POR USO ABUSIVO</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel se reserva el derecho, ejercitable en cualquier momento a cobrar una indemnizaci&oacute;n del precio &iacute;ntegro por los da&ntilde;os causados como consecuencia de contravenir las presentes Condiciones de Uso o Normas de funcionamiento. Mitorneodepadel tambi&eacute;n podr&aacute; cobrar dicha indemnizaci&oacute;n, tanto al administrador de el torneo, jugadores, patrocinadores como terceras personas o empresas que faciliten con su ayuda el uso abusivo de los servicios, podr&aacute;n ser requeridos para el pago de esta indemnizaci&oacute;n.</label>
                <label class="titulo_condiciones">11. VARIOS</label>
                <label class="titulo_condiciones">A. Modificaciones en el Servicio y Condiciones de Uso</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel se reserva el derecho a realizar cambios en el Portal, pudiendo modificar, suprimir e incluir, unilateralmente y sin previo aviso, nuevos contenidos as&iacute; como la forma en que estos aparezcan presentados y localizados..</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Asimismo, Mitorneodepadel se reserva el derecho a realizar cambios las presentes Condiciones de Uso en cualquier momento. El usuario quedar&aacute; sujeto a las nuevas Condiciones de Uso que hayan sido publicadas en el momento en que acceda o utilice los servicios del Portal.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Si alguna de las presentes condiciones resulta invalidada, nula o inaplicable por cualquier motivo, dicha condici&oacute;n quedar&aacute; excluida y no afectar&aacute; a la validez ni la aplicabilidad del resto de condiciones.</label>
                <label class="titulo_condiciones">B. Precios de los Servicios</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los precios de los servicios ser&aacute;n establecidos en las correspondientes p&aacute;ginas del Portal para cada servicio.</label>
                <label class="titulo_condiciones">C. Menores de Edad</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Con car&aacute;cter general, para hacer uso de los Servicios del Portal los menores de edad deben haber obtenido previamente la autorizaci&oacute;n de sus padres, tutores o representantes legales, quienes ser&aacute;n responsables de todos los actos realizados a trav&eacute;s del Portal por los menores a su cargo.</label>
                <label class="titulo_condiciones">12. DURACI&Oacute;N Y TERMINACI&Oacute;N</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;La prestaci&oacute;n de los servicios y/o contenidos del Portal tiene una duraci&oacute;n indefinida.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Sin perjuicio de lo anterior, y adem&aacute;s de por las causas establecidas legalmente, Mitorneodepadel est&aacute; facultada para dar por terminada, suspender o interrumpir unilateralmente, en cualquier momento y sin necesidad de preaviso, la prestaci&oacute;n del servicio y del Portal y/o cualquiera de los servicios..</label>
                <label class="titulo_condiciones">13. JURISDICCI&Oacute;N</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;La ley aplicable en caso de disputa o conflicto de interpretaci&oacute;n de los t&eacute;rminos que conforman estas Condiciones de Uso, as&iacute; como cualquier cuesti&oacute;n relacionada con los servicios del Portal, ser&aacute; la ley espa&ntilde;ola..</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Para la resoluci&oacute;n de cualquier controversia que pudiera surgir con ocasi&oacute;n del uso del Portal y sus servicios, las partes acuerdan someterse a la jurisdicci&oacute;n de los Juzgados y Tribunales de la ciudad de Alicante (Espa&ntilde;a), y sus superiores jer&aacute;rquicos, con expresa renuncia a otros fueros si lo tuvieren y fueran diferentes de los rese&ntilde;ados..</label>
                <label class="titulo_condiciones">NORMAS DE FUNCIONAMIENTO</label>
                 <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El portal no se hace responsable de cualquier funcionamiento incorrecto del sistema ya bien sea por error en la conexi&oacute;n de internet o por problemas con el dispositivo.</label>
                <label class="titulo_condiciones">1. Administrador de torneo</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador se compromete a realizar las gestiones de la manera m&aacute;s responsable y justa posible.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador est&aacute; de acuerdo en asumir toda la responsabilidad legal sobre los torneos que gestiona o ha gestionado.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador acepta que los torneos gratuitos finalizados o abandonados por 1 mes son eliminados autom&aacute;ticamente del sistema.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Por seguridad, el sistema genera noticias autom&aacute;ticas con todas las modificaciones realizadas sobre los torneos y divisiones.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Por seguridad, para activar el modo de pagos online a trav&eacute;s de paypal es obligatorio solicitarlo a atencionalcliente(arroba)mitorneodepadel.es adjuntando una foto/fotocopia del NIF o NIE del administrador/a.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador tiene el derecho de admisi&oacute;n sobre los participantes de su torneo.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador est&aacute; obligado de realizar la devoluci&oacute;n del pago (si lo hubiera) por la misma v&iacute;a (online o presencial) que lo ha recibido en caso de no admitir en su torneo a un equipo inscrito.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador tiene el derecho a decidir si devolver o no el importe de la inscripci&oacute;n s&oacute;lo en el caso de que lo solicite el equipo inscrito y no tengan un motivo firme para realizar dicha devoluci&oacute;n.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador acepta ser el &uacute;nico responsable legal de los pagos online o presenciales recibidos por parte de los jugadores que se inscriben en sus torneos.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador acepta que esta web pueda facilitar sus datos personales a jugadores s&oacute;lo en caso de situaci&oacute;n irregular o indicios de fraude con pagos (online y presencial) recibidos por jugadores, para que los jugadores puedan tomar las medidas legales pertinentes.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador acepta que la eliminaci&oacute;n de su cuenta solo ser&aacute; posible cuando todas los torneos est&eacute;n finalizados o no tengan inscritos, evitando de esta manera perjudicar o realizar actividades fraudulentas sobre los jugadores.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador acepta que por seguridad est&aacute; web guarde un hist&oacute;rico de sus cambios en datos personales.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;En esta web sus datos personales son totalmente privados y no ser&aacute;n utilizados para ning&uacute;n fin ajeno a esta web.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web tiene el derecho de inhabilitar a cualquier administrador que no respete las condiciones legales de esta web o realice actividades fraudulentas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web almacena la Ip al acceder al panel de usuario s&oacute;olo y exclus&iacute;vamente para utilizar en casos de acciones fraudulentas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web no se hace responsable ante el delito de robo de cualquier informaci&oacute;n alojada en nuestra base de datos, y emprender&aacute; acciones legales contra los atacantes.</label>
                <label class="titulo_condiciones">2. Jugador</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El jugador/a debe asegurarse de inscribirse en el torneo adecuado y conocer al administrador, organizaci&oacute;n o club que lo gestiona sobre todo si requiere pago online por inscripci&oacute;n.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El jugador/a dispone de un panel de control personalizado en el que podr&aacute; gestionar algunos de sus datos personales, foto de perfil, justificantes de pagos y ver las estad&iacute;sticas de sus torneos inscritos.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Para inscribirse en cualquier torneo es necesario ser mayor de 18 a&ntilde;os, o est&aacute; confirmando que sus padres/tutores est&aacute;n informados y son responsables de su inscripci&oacute; en cualquier torneo de www.mitorneodepadel.es que queda exenta de cualquier responsabilidad sobre los menores que utilicen el portal.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Al registrarse como nuevo jugador, &eacute;ste debe saber que est&aacute; aceptando que los administradores de los torneos en los que se inscribe tienen acceso a algunos de tus datos, utilizados expresamente para contactar con usted en temas relacionados con el torneo.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Este portal recomienda tener acceso al correo electr&oacute;nico con el que se ha efectuado el registro en esta web, y revisar la bandeja de entrada con frecuencia, ya que podr&aacute; recibir e-mails sobre sus torneos por parte de administrador/es.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Con la inscripci&oacute;n el jugador/a acepta recibir informaci&oacute;n acerca de los torneos inscritos incluyendo informaci&oacute;n importante sobre mitorneodepadel.es.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Una vez el jugador/a decide eliminar su perfil, todos los datos ser&aacute;n eliminados inmediatamente y de forma irreversible.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los datos del perfil de los jugadores/as alojados en este portal son totalmente privados y solo se utilizar&aacute;n en esta web, no ser&aacute;n facilitados a terceros bajo ning&uacute;n concepto.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El/La jugador/a participante se compromete a utilizar los servicios ofrecidos de manera responsable y de acuerdo a nuestras normas o podr&aacute; ser eliminado del portal.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El/la jugador/a se compromete a facilitar el correcto funcionamiento de los torneos inscritos y no entorpecerlos o dificultarlos.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El/la jugador/a debe hacer un uso responsable de la comunicaci&oacute;n v&iacute;a e-mail con el/los administrador/es y acepta que es el responsable del contenido enviado, eximiendo de toda responsabilidad al portal www.mitorneodepadel.es.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web se ha desarrollado estableciendo restricciones para ofrecer la m&aacute;xima seguridad para los/las jugadores/as participantes.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web ofrece la posibilidad de que los jugadores/as realicen el pago online de inscripci&oacute;n al administrador de el torneo a trav&eacute;s de Paypal, s&oacute;lo si el administrador configura los requerimientos necesarios, siendo el aldministrador el total responsable ya que es el que recibe el pago.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El pago online de inscripciones se ha de realizar solo una vez por un jugador/a del equipo.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;La devoluci&oacute;n de pagos online se han de tramitar con el administrador, este solicita la eliminaci&oacute;n y los jugadores deben comprobar que han recibido la devoluci&oacute;n v&iacute;a PayPal, y una vez verificada la gesti&oacute;n de devoluci&oacute;n alguno de los miembros del equipo deben pulsar sobre 'Si' sobre el correo electr&oacute;nico recibido e inmediatamente se eliminar&aacute; la inscripci&oacute;n, de lo contrario pulse 'No'.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Si el equipo solicita la devoluci&oacute;n una vez realizado el pago de la inscripci&oacute;n el administrador tiene el derecho a decidir si realizar la devoluci&oacute;n o no.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El administrador tiene el derecho de adminsi&oacute;n sobre los equipos inscritos, pero si ha recibido un pago online o presencial y no desea admitir una participaci&oacute;n est&aacute; obligado a realizar la devoluci&oacute;n &iacute;ntegra del importe de pago.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El jugador acepta que para que se active la eliminaci&oacute;n de su perfil solo ser&aacute; posible cuando todos los torneos en los que est&aacute; inscrito se encuentren finalizados o las inscripciones no est&eacute;n pagadas, evitando de esta manera alterar el torneo o realizar actividades fraudulentas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web no recibe comisiones ni pagos de los jugadores/as, por lo tanto no se hace responsable de ning&uacute;n pago online o presencial que los jugadores/as realicen a los administradores de el torneo en la que se han inscrito.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Este portal web se compromete ante indicios o casos fraudulentos a facilitar los datos necesarios del infractor para formalizar una posible denuncia judicial.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta portal web almacena la Ip al acceder al panel de jugador s&oacute;olo y exclus&iacute;vamente para utilizar en casos de acciones fraudulentas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta portal web no se hace responsable ante el delito de robo de cualquier informaci&oacute;n alojada en nuestra base de datos, y emprender&aacute; acciones legales contra los atacantes.</label>
                <label class="titulo_condiciones">3. Patrocinador</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El Patrocinador est&aacute; de acuerdo en asumir toda la responsabilidad legal sobre el contenido de las im&aacute;genes y enlaces insertados.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web dispone de un control de anuncios para asegurar siempre la publicaci&oacute;n equitativa de publicidad para cada ciudad.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Puede realizar tantos anuncios por ciudad como desee.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los anuncios pueden verse congelados en el caso de no haber en ese momento torneos activos para la ciudad seleccionada, tendr&aacute; la opci&oacute;n de cambiar a una ciudad m&aacute;s cercana o esperar nuevos torneos activos, el tiempo de espera ser&aacute; a&ntilde;adido autom&aacute;ticamente.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los precios de anuncio var&iacute;an en funci&oacute;n de los torneos que tiene cada ciudad.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;En esta web sus datos personales son totalmente privados y no ser&aacute;n utilizados para ning&uacute;n fin ajeno a esta web.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;En caso de cualquier indicio de actividad delictiva, esta web podr&aacute; facilitar sus datos personales para realizar las acciones legales oportunas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El pago de los anuncios se realiza a trav&eacute;s de la platarforma de pagos seguros PayPal.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El patrocinador acepta que la eliminaci&oacute;n de su cuenta solo ser&aacute; posible cuando todos los anuncios est&eacute;n finalizados o no se hayan realizado el pago.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web puede cancelar en cualquier momento un anuncio en el que se hayan realizado irregularidades en el pago.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Una vez que su anuncio es publicado ya no es posible la devoluci&oacute;n del pago realizado.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los anuncios pueden quedarse en estado congelado debido a la falta de torneos activos para una ciudad, puede elegir cambiar a una ciudad m&aacute;s cercana o esperar torneos activos, el tiempo de congelaci&oacute;n se le abonar&aacute; autom&aacute;ticamente a la fecha de fin del anuncio.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web tiene el derecho de inhabilitar a cualquier patrocinador que no respete las condiciones legales de esta web o realice actividades fraudulentas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Esta web almacena la Ip al acceder al panel de patrocinador s&oacute;olo y exclus&iacute;vamente para utilizar en casos de acciones fraudulentas.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp; Esta web no se hace responsable ante el delito de robo de cualquier informaci&oacute;n alojada en nuestra base de datos, y emprender&aacute; acciones legales contra los atacantes.</label>                
                <label class="titulo_condiciones">POLITICA DE PRIVACIDAD DE MITORNEODEPADEL Y USO DE COOKIES</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;La presente Pol&iacute;tica de Privacidad tiene por objeto describir la pol&iacute;tica de protecci&oacute;n de datos de Mitorneodepadel (en adelante, "Mitorneodepadel") propietaria de las p&aacute;ginas web ubicadas bajo el dominio www.mitorneodepadel.com, www.mitorneodepadel.es (en adelante, el "Portal").<!-- con la direcci&oacute;n Mitorneodepadel, Apartado postal 29059, Madrid y con N&uacute;mero de Identificaci&oacute;n Fiscal B86326758 e inscrita en el Registro Mercantil de Madrid, Tomo 29473, Folio 100, Secci&oacute;n 8, Hoja M530465..--></label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los datos aportados por los usuarios a Mitorneodepadel son incluidos en nuestros ficheros registrados ante la Agencia Espa&ntilde;ola de Protecci&oacute;n de Datos (AEPD). La AEPD se encarga de velar por el cumplimiento de las leyes sobre privacidad y protecci&oacute;n de datos y de garantizar la seguridad y privacidad de sus datos.</label>
                <label class="titulo_condiciones">1. INFORMACI&Oacute;N SOBRE DATOS RECABADOS POR MITORNEODEPADEL</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los servidores de Mitorneodepadel est&aacute;n situados en Espa&ntilde;a y recabamos y almacenamos en ficheros tanto informaci&oacute;n facilitada por los usuarios como datos obtenidos a trav&eacute;s de la utilizaci&oacute;n del Portal.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Por tanto, mediante el acceso al Portal o la utilizaci&oacute;n de sus servicios el usuario consiente y autoriza expresamente a que los datos de car&aacute;cter personal facilitados, sean incorporados a la base de datos de Mitorneodepadel, y que sean tratados exclusivamente de conformidad con los fines establecidos en la presente Pol&iacute;tica de Privacidad, as&iacute; como las Condiciones de Uso.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;En el supuesto de que el usuario tuviera que facilitar a Mitorneodepadel datos personales de terceros, deber&aacute; asegurarse de contar con el consentimiento expreso de dicho tercero, habi&eacute;ndole informado de a qui&eacute;n se van a facilitar los datos, la finalidad y la posibilidad de que Mitorneodepadel se ponga en contacto con ellos.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;La falta de suministro de aquellos datos que sean obligatorios para la prestaci&oacute;n de los servicios o el suministro de datos incorrectos, inexactos o no actualizados imposibilitar&aacute; la prestaci&oacute;n de los servicios por parte de Mitorneodepadel.</label>
                <label class="titulo_condiciones">1) INFORMACI&Oacute;N FACILITADA POR EL USUARIO</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Para administrar, jugar o patrocinar un torneo, el usuario tiene que proporcionar datos personales como, por ejemplo, la direcci&oacute;n del correo electr&oacute;nico, el nombre y como usuario administrador de torneos puede que el nif. Para disfrutar de determinados servicios que ofrece Mitorneodepadel en su Portal, es posible que sea redirigido a la plataforma de pago paypal para realizar pagos y posteriormente volver a Mitorneodepadel para verificar el pago.
Mitorneodepadel se reserva el derecho de comprobar la identidad de los usuarios mediante verificaci&oacute;n por tel&eacute;fono o e-mail.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los contactos establecidos en Mitorneodepadel ser&aacute; a trav&eacute;s de su direcci&oacute;n del correo electr&oacute;nico y nunca se facilitar&aacute; el correo electr&oacute;nico del emisor.</label>
                <label class="titulo_condiciones">2) DATOS OBTENIDOS A TRAV&Eacute;S DE LA UTILIZACI&Oacute;N DE NUESTROS SERVICIOS</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Cada vez que uses nuestros servicios o que consultes nuestro contenido, es posible que obtengamos y que almacenemos determinada informaci&oacute;n en los registros del servidor de forma autom&aacute;tica. Estos datos podr&aacute;n incluir:.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;informaci&oacute;n sobre el acceso (por ejemplo, si accedes des pc, m&oacute;vil, tablet...etc) y tipo de navegador,</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;informaci&oacute;n sobre el acceso de los usuarios para evitar suplantaci&oacute;n de identidad,</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;la direcci&oacute;n IP.</label>
                <label class="titulo_condiciones">3) COOKIES</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Este portal no utiliza cookies.</label>
                <label class="titulo_condiciones">4) USO DE LOS DATOS RECOGIDOS</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los datos que recogemos a trav&eacute;s de todos nuestros servicios se utilizan para prestar, mantener, personalizar, proteger y mejorar los servicios de Mitorneodepadel, desarrollar nuevos servicios y velar por la protecci&oacute;n de Mitorneodepadel y de nuestros usuarios.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Todos los datos facilitados que no tienen car&aacute;cter personal, como por ejemplo, la descripci&oacute;n del bien, del animal, del servicio, etc., las caracter&iacute;sticas y los atributos del mismo, el precio, el nombre de contacto y el n&uacute;mero de tel&eacute;fono son, como es obvio por la naturaleza del servicio, p&uacute;blicos.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los t&eacute;rminos recogidos en la Pol&iacute;tica de Privacidad y, en concreto, el deber de confidencialidad son de obligado cumplimiento para todos los destinatarios de la informaci&oacute;n recogida, incluyendo el personal contratado por Mitorneodepadel y aquellos terceros, que en virtud de un contrato de prestaci&oacute;n de servicios, tengan acceso a datos de car&aacute;cter personal y a los equipos o sistemas de Mitorneodepadel.</label>
                <label class="titulo_condiciones">5) CESI&Oacute;N DE DATOS A TERCEROS</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel no comunica, vende, alquila o comparte los datos de car&aacute;cter personal de los usuarios con empresas, organizaciones o personas f&iacute;sicas ajenas a Mitorneodepadel.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Dicho consentimiento no ser&aacute; necesario para la comunicaci&oacute;n de datos en los supuestos en los que la Ley los permite expresamente.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Si Mitorneodepadel participa en una fusi&oacute;n, adquisici&oacute;n o venta de activos, nos aseguraremos de mantener la confidencialidad de los datos personales e informaremos a los usuarios afectados antes de que sus datos personales sean transferidos o pasen a estar sujetos a una pol&iacute;tica de privacidad diferente.</label>
                <label class="titulo_condiciones">6) UTILIZACI&Oacute;N DE LA INFORMACI&Oacute;N EN EL PORTAL</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los usuarios jugadores de Mitorneodepadel solo pueden utilizar los datos de car&aacute;cter personal publicados en el Portal para tratar con usuarios administradores de torneos y viceversa, no para enviar informaci&oacute;n publicitaria no solicitada o correo basura ni recoger datos de car&aacute;cter personal de una persona que no lo haya autorizado.</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Mitorneodepadel puede revisar o filtrar autom&aacute;tica o manualmente los mensajes de los usuarios enviados a trav&eacute;s del Portal para controlar las actividades maliciosas o el contenido prohibido.</label>
                <label class="titulo_condiciones">7) ACCESO, RECTIFICACI&Oacute;N, CANCELACI&Oacute;N Y OPOSICI&Oacute;N</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;El usuario puede acceder y/o rectificar la mayor&iacute;a de sus datos de car&aacute;cter personal accediendo a los mismos a trav&eacute;s del Portal. Para acceder o rectificar cualquier otro dato que no pueda consultarse a trav&eacute;s de la p&aacute;gina web, as&iacute; como ejercitar los derechos de cancelaci&oacute;n u oposici&oacute;n, el usuario puede comunicarse con info(arroba)mitorneodepadel.es. Mitorneodepadel cancelar&aacute; los datos de car&aacute;cter personal cuando ya no se necesitan para los fines descritos anteriormente. La cancelaci&oacute;n da lugar al bloqueo de los datos, conserv&aacute;ndose &uacute;nicamente aqu&eacute;llos necesarios para la atenci&oacute;n de las posibles responsabilidades nacidas del tratamiento, durante el plazo de prescripci&oacute;n de &eacute;stas.</label>
                <label class="titulo_condiciones">8) SEGURIDAD</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;Los servidores de Mitorneodepadel est&aacute;n ubicadas a trav&eacute;s de una empresa externa que aseguran la protecci&oacute;n de sus servidores y de los datos que los contienen.</label>
				<label class="titulo_condiciones">9) MODIFICACIONES</label>
                <label id="caja_texto_largo" class="hvr-bounce-to-right">&bull;&nbsp;La Pol&iacute;tica de Privacidad de Mitorneodepadel se podr&aacute; modificar en cualquier momento. No limitaremos los derechos que corresponden al usuario con arreglo a la presente Pol&iacute;tica de Privacidad sin tu expreso consentimiento. Publicaremos todas las modificaciones de la presente Pol&iacute;tica de Privacidad en esta p&aacute;gina y, si son significativas, efectuaremos una notificaci&oacute;n m&aacute;s destacada (por ejemplo, te enviaremos una notificaci&oacute;n por correo electr&oacute;nico si la modificaci&oacute;n afecta a determinados servicios).</label>  
            </div>
        </div>
    </div>
    <div class="derecho">&nbsp;</div>
<?php
pie();
?>
</div>
<?php
cuerpo_fin();
?>
